AUTO_RESUME: true
USE_SWEEP: false
OUTPUT_DIR: "results/012/"
WORKERS: 6

MODEL:
    NAME: "swing_net"
    PRETRAINED: ""
    IMAGE_SIZE:
        - 256
        - 256

    PHASE_NUM: 9 # include other
    
    # swing net param which using lstm
    BACKBONE: "r3d"
    WIDTH_MULT: 1
    LSTM_LAYERS: 1
    LSTM_HIDEEN: 256
    BIDIRECTIONAL: true

    # phase net param which using tcn
    # N_FEATURES: 64
    # N_STAGES: 4
    # N_LAYERS: 10

DATASET:
    NAME: "golfdb"
    DATA_FORMAT: "mp4"
    ROOT: "data/golfdb/"
    VID_DIR: "data/golfdb/videos_160/"
    TRAIN_FILE: "data/golfdb/train_split_1.pkl"
    VAL_FILE: "data/golfdb/val_split_1.pkl"

    SHUFFLE: true
    PIN_MEMORY: false
    DROP_LAST: true

    SEQ_LENGTH: 64
    USE_LABEL_DISTRIBUTION: false
    USE_OTHER_PHASE_LABEL: false
    SIGMA_LABEL_DISTRIBUTION: 0.3
    USE_MIDDLE_PHASE_LABEL_ONLY: true
    USE_TEMPORAL_LABEL_SMOOTHING: false

LOSS:
    USE_TARGET_WEIGHT: false
    WEIGHTS: [1, 0, 0, 0]
    CE: true
    CE_WEIGHT: [0.125, 0.125, 0.125, 0.125, 0.125, 0.125,0.125, 0.125, 0.125]
    FOCAL: false
    FOCAL_WEIGHT: 1.0
    GSTMSE: false
    GSTMSE_WEIGHT: 1.0
    TMSE: false
    TMSE_WEIGHT: false
    THRESHOLD: 4
    IGNORE_INDEX: 255

TRAIN:
    EPOCHS: 500
    BATCH_SIZE: 8
    OPTIMIZER: "adam"
    LR: 0.0005
    SEQ_LENGTH: 64

DEBUG:
    DEBUG: true
