AUTO_RESUME: true
USE_SWEEP: false
OUTPUT_DIR: "results/010/"
WORKERS: 6

MODEL:
    NAME: "swing_net"
    PRETRAINED: ""
    IMAGE_SIZE:
        - 256
        - 256

    PHASE_NUM: 9 # include other
    WIDTH_MULT: 1
    LSTM_LAYERS: 1
    LSTM_HIDEEN: 256
    BIDIRECTIONAL: true
    DROPOUT: false
    SEQ_LENGTH: 64

DATASET:
    NAME: "golfdb"
    DATA_FORMAT: "mp4"
    ROOT: "data/golfdb/"
    VID_DIR: "data/golfdb/videos_160/"
    TRAIN_FILE: "data/golfdb/train_split_1.pkl"
    VAL_FILE: "data/golfdb/val_split_1.pkl"

    SHUFFLE: true
    PIN_MEMORY: false
    DROP_LAST: true

    SEQ_LENGTH: 64
    USE_LABEL_DISTRIBUTION: false
    USE_OTHER_PHASE_LABEL: false
    SIGMA_LABEL_DISTRIBUTION: 0.3
    USE_MIDDLE_PHASE_LABEL_ONLY: true

LOSS:
    USE_TARGET_WEIGHT: false
    CE: true
    FOCAL: false
    FOCAL_WEIGHT: 1.0
    GSTMSE: false
    GSTMSE_WEIGHT: 1.0
    TMSE: false
    TMSE_WEIGHT: false

TRAIN:
    EPOCHS: 500
    BATCH_SIZE: 1
    OPTIMIZER: "adam"
    LR: 0.0005

DEBUG:
    DEBUG: true
