method: bayes
metric:
    name: train_loss
    goal: minimize
parameters:
  TRAIN.LR:
        min: 0.001
        max: 0.1
    TRAIN.OPTIMIZER:
        values: ["adam", "sgd"]
    MODEL.DROPOUT:
        values: [true, false]
